field: f8b67eb1-be12-4350-862a-876bc6d5df0b # Products
fieldLayouts:
  02caa231-27fa-404d-b739-dcbb2da539c3:
    tabs:
      -
        elements:
          -
            fieldUid: 6d6752d8-ce94-479f-930c-20cd4bbfd564 # Beer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4f86acec-2e17-45fe-b9a1-441f3a9bcb23 # Notes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a81c4e2e-fbff-48e0-8a5d-7c73a22ebf66 # Pairings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 40e0c894-65a1-41b1-9c36-a7023d0d9939 # Formats
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5922fdec-bff9-41b0-add7-f3c5f3be524e # ABV
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4f86acec-2e17-45fe-b9a1-441f3a9bcb23: # Notes
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: notes
    instructions: ''
    name: Notes
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6d6752d8-ce94-479f-930c-20cd4bbfd564: # Beer
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: beer
    instructions: ''
    name: Beer
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  40e0c894-65a1-41b1-9c36-a7023d0d9939: # Formats
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: formats
    instructions: ''
    name: Formats
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '3'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5922fdec-bff9-41b0-add7-f3c5f3be524e: # ABV
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: abv
    instructions: ''
    name: ABV
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a81c4e2e-fbff-48e0-8a5d-7c73a22ebf66: # Pairings
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: pairings
    instructions: ''
    name: Pairings
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: beer
name: Beer
sortOrder: 1
