columnSuffix: sxevaiiy
contentColumnType: text
fieldGroup: ab9eeee8-dea7-4ca9-9b2f-6d69b49f858e # Products
handle: abv
instructions: ''
name: ABV
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
