columnSuffix: null
contentColumnType: string
fieldGroup: ae71d09c-3bb9-4136-8afb-1d7ca8a8d9dd # Stockists
handle: beersStocked
instructions: ''
name: 'Beers Stocked'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources:
    - 'section:160e55f6-25ba-4d21-a6d7-52b34dbea2d6' # Product
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
