columnSuffix: vgstnumr
contentColumnType: string
fieldGroup: ab9eeee8-dea7-4ca9-9b2f-6d69b49f858e # Products
handle: formats
instructions: ''
name: Formats
searchable: false
settings:
  multi: true
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - 330ml
        -
          - value
          - 330ml
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 500ml
        -
          - value
          - 500ml
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 660ml
        -
          - value
          - 660ml
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '4pk 330ml'
        -
          - value
          - '4pk 330ml'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '6pk 330ml'
        -
          - value
          - '6pk 330ml'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '12pk 330ml'
        -
          - value
          - '12pk 330ml'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\MultiSelect
