columnSuffix: null
contentColumnType: string
fieldGroup: 014ddf4d-4c06-4fe8-b8ed-3191a53fbf0a # Home Page
handle: heroImage
instructions: ''
name: 'Hero Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:0538fb61-54f5-42ee-b316-03f27084d446' # Uploads
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: thumbs
  restrictFiles: '1'
  selectionLabel: 'Add a background image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:0538fb61-54f5-42ee-b316-03f27084d446' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:0538fb61-54f5-42ee-b316-03f27084d446' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
