columnSuffix: pciaghya
contentColumnType: 'decimal(16,6)'
fieldGroup: ae71d09c-3bb9-4136-8afb-1d7ca8a8d9dd # Stockists
handle: latitude
instructions: ''
name: Latitude
searchable: false
settings:
  decimals: '6'
  defaultValue: null
  max: null
  min: null
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
