columnSuffix: null
contentColumnType: string
fieldGroup: d064f0cc-5bcb-4623-88cc-905ffe15c5fc # Top Level
handle: navigation
instructions: ''
name: Navigation
searchable: false
settings:
  contentTable: '{{%matrixcontent_navigation}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
