columnSuffix: null
contentColumnType: string
fieldGroup: ae71d09c-3bb9-4136-8afb-1d7ca8a8d9dd # Stockists
handle: stockists
instructions: ''
name: Stockists
searchable: false
settings:
  contentTable: '{{%matrixcontent_stockists}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
