dateModified: 1648403662
email:
  fromEmail: shaunlindsley@gmail.com
  fromName: Goodbeers
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0a52d1f1-197c-4c0a-a6db-69018f4353e1: Common # Common
    0e7b6f1d-8852-422b-a217-3ac3cd450215: 'Hero Title' # Hero Title
    014ddf4d-4c06-4fe8-b8ed-3191a53fbf0a: 'Home Page' # Home Page
    179f0ea6-bca7-43ae-add7-7648376d300d: 'Hero Image' # Hero Image
    0538fb61-54f5-42ee-b316-03f27084d446: Uploads # Uploads
    001221df-1213-4667-90cf-4e5cef5c3883: Goodbeers # Goodbeers
    257443c7-9a91-4a24-89c2-0607e7026ea7: Home # Home
    d443204d-b01f-4a2a-bc62-3a486242edc2: Goodbeers # Goodbeers
    d784302c-b13c-4581-9bbf-3689c3f72723: Home # Home
system:
  edition: solo
  live: true
  name: Goodbeers
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
