defaultPlacement: end
enableVersioning: true
handle: contact
name: Contact
propagationMethod: all
siteSettings:
  d443204d-b01f-4a2a-bc62-3a486242edc2: # Goodbeers
    enabledByDefault: true
    hasUrls: true
    template: contact/contact.twig
    uriFormat: contact
structure:
  maxLevels: null
  uid: 7b15a35f-ea41-45c3-a75f-d9ddb25504c7
type: structure
