defaultPlacement: end
enableVersioning: true
handle: stockists
name: Stockists
propagationMethod: all
siteSettings:
  d443204d-b01f-4a2a-bc62-3a486242edc2: # Goodbeers
    enabledByDefault: true
    hasUrls: true
    template: stockists/_entry
    uriFormat: '{slug}'
type: channel
