defaultPlacement: end
enableVersioning: true
handle: termsAndConditions
name: 'Terms and Conditions'
propagationMethod: all
siteSettings:
  d443204d-b01f-4a2a-bc62-3a486242edc2: # Goodbeers
    enabledByDefault: true
    hasUrls: true
    template: 't&c.twig'
    uriFormat: terms-and-conditions
type: single
